name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  rust:
    name: check, fmt & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt-get install -y libx11-dev libxi-dev libgl1-mesa-dev

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- -Z unstable-options --include-ignored

  wasm:
    name: wasm compile & deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: cargo build --release --example wasm
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --example wasm --target wasm32-unknown-unknown

      - name: create www dir
        run: |
          mkdir www
          cp target/wasm32-unknown-unknown/release/examples/*.wasm www
          cp examples/wasm/*.html www

      - name: deploy to github pages
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: www
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
